import Bot from "../core/Client"

function SetRandomStatus() {

    //? Get Track from Beginning and push to back
    const Track = Tracks[0]
    Tracks = Tracks.slice(1)
    Tracks.push(Track)

    //? Calculate Time to Wait
    let Time = 0
    Track.time.split(":").forEach((str, index) => {
        Time += index === 0
            ? Number(str) * 60  // Is Minutes
            : Number(str)       // Is Seconds
    })

    //? Set Bot Status
    Bot.user.setPresence({
        "activities": [{
            "type": "LISTENING",
            "name": `${Track.name} by Kanye West`
        }]
    })

    //? Change on Timeout
    console.debug(`Set Status to "${Track.name}", Next Track is "${Tracks[0].name}", Waiting for ${Time} seconds, `)
    setTimeout(SetRandomStatus, Time * 1000);
}

Bot.on("ready", SetRandomStatus)

let Tracks = [
    { "name": "Welcome To The Jungle", "time": "2:54" },
    { "name": "Who Gon Stop Me", "time": "4:16" },
    { "name": "Murder To Excellence", "time": "5:00" },
    { "name": "Made In America", "time": "4:52" },
    { "name": "Why I Love You", "time": "3:21" },
    { "name": "Illest Motherf**ker Alive", "time": "8:23" },
    { "name": "H•A•M", "time": "4:35" },
    { "name": "Primetime", "time": "3:19" },
    { "name": "The Joy", "time": "5:17" },
    { "name": "Dark Fantasy", "time": "4:40" },
    { "name": "Gorgeous", "time": "5:57" },
    { "name": "POWER", "time": "4:52" },
    { "name": "All Of The Lights (Interlude)", "time": "1:02" },
    { "name": "All Of The Lights", "time": "4:59" },
    { "name": "Monster", "time": "6:18" },
    { "name": "So Appalled", "time": "6:37" },
    { "name": "Devil In A New Dress", "time": "5:51" },
    { "name": "Runaway", "time": "9:07" },
    { "name": "Hell Of A Life", "time": "5:27" },
    { "name": "Blame Game", "time": "7:49" },
    { "name": "Lost In The World", "time": "4:16" },
    { "name": "Who Will Survive In America", "time": "1:38" },
    { "name": "Good Morning", "time": "3:15" },
    { "name": "Champion", "time": "2:47" },
    { "name": "Stronger", "time": "5:11" },
    { "name": "I Wonder", "time": "4:03" },
    { "name": "Good Life", "time": "3:27" },
    { "name": "Can't Tell Me Nothing", "time": "4:31" },
    { "name": "Barry Bonds", "time": "3:24" },
    { "name": "Drunk and Hot Girls", "time": "5:13" },
    { "name": "Flashing Lights", "time": "3:57" },
    { "name": "Everything I Am", "time": "3:47" },
    { "name": "The Glory", "time": "3:32" },
    { "name": "Homecoming", "time": "3:23" },
    { "name": "Big Brother", "time": "4:47" },
    { "name": "Good Night - Bonus Track", "time": "3:05" },
    { "name": "Say You Will", "time": "6:17" },
    { "name": "Welcome To Heartbreak", "time": "4:22" },
    { "name": "Heartless", "time": "3:31" },
    { "name": "Amazing", "time": "3:58" },
    { "name": "Love Lockdown", "time": "4:30" },
    { "name": "Paranoid", "time": "4:37" },
    { "name": "RoboCop", "time": "4:34" },
    { "name": "Street Lights", "time": "3:09" },
    { "name": "Bad News", "time": "3:58" },
    { "name": "See You In My Nightmares", "time": "4:18" },
    { "name": "Coldest Winter", "time": "2:44" },
    { "name": "Pinocchio Story", "time": "6:01" },
    { "name": "Wake Up Mr. West", "time": "0:41" },
    { "name": "Heard 'Em Say", "time": "3:23" },
    { "name": "Touch The Sky", "time": "3:56" },
    { "name": "Gold Digger", "time": "3:27" },
    { "name": "Drive Slow", "time": "4:32" },
    { "name": "My Way Home", "time": "1:43" },
    { "name": "Crack Music", "time": "4:30" },
    { "name": "Roses", "time": "4:05" },
    { "name": "Bring Me Down", "time": "3:18" },
    { "name": "Addiction", "time": "4:27" },
    { "name": "Diamonds From Sierra Leone - Remix", "time": "3:53" },
    { "name": "We Major", "time": "7:28" },
    { "name": "Hey Mama", "time": "5:05" },
    { "name": "Celebration", "time": "3:18" },
    { "name": "Gone", "time": "5:33" },
    { "name": "Diamonds From Sierra Leone - Bonus Track", "time": "3:58" },
    { "name": "Late", "time": "3:50" },
    { "name": "Intro", "time": "0:19" },
    { "name": "We Don't Care", "time": "3:59" },
    { "name": "Graduation Day", "time": "1:21" },
    { "name": "All Falls Down", "time": "3:43" },
    { "name": "I'll Fly Away", "time": "1:09" },
    { "name": "Spaceship", "time": "5:24" },
    { "name": "Jesus Walks", "time": "3:13" },
    { "name": "Never Let Me Down", "time": "5:24" },
    { "name": "Get Em High", "time": "4:49" },
    { "name": "Workout Plan", "time": "0:46" },
    { "name": "The New Workout Plan", "time": "5:22" },
    { "name": "Slow Jamz", "time": "5:16" },
    { "name": "Breathe In Breathe Out", "time": "4:06" },
    { "name": "School Spirit", "time": "3:02" },
    { "name": "Two Words", "time": "4:26" },
    { "name": "Through The Wire", "time": "3:41" },
    { "name": "Family Business", "time": "4:38" },
    { "name": "Last Call", "time": "12:40" },
    { "name": "Donda Chant", "time": "0:52" },
    { "name": "Hurricane", "time": "4:03" },
    { "name": "Moon", "time": "2:36" },
    { "name": "Life Of The Party (with André 3000)", "time": "6:31" },
    { "name": "Off The Grid", "time": "5:39" },
    { "name": "Jail", "time": "4:57" },
    { "name": "Praise God", "time": "3:46" },
    { "name": "Come to Life", "time": "5:10" },
    { "name": "Believe What I Say", "time": "4:02" },
    { "name": "No Child Left Behind", "time": "2:58" },
    { "name": "Up From The Ashes", "time": "2:42" },
    { "name": "Remote Control pt 2", "time": "5:23" },
    { "name": "God Breathed", "time": "5:33" },
    { "name": "Lord I Need You", "time": "2:42" },
    { "name": "24", "time": "3:17" },
    { "name": "Junya", "time": "2:27" },
    { "name": "Never Abandon Your Family", "time": "3:27" },
    { "name": "Donda", "time": "2:08" },
    { "name": "Keep My Spirit Alive", "time": "3:41" },
    { "name": "Jesus Lord pt 2", "time": "12:05" },
    { "name": "Heaven and Hell", "time": "2:25" },
    { "name": "Remote Control", "time": "3:18" },
    { "name": "Tell The Vision", "time": "1:44" },
    { "name": "Jonah", "time": "3:15" },
    { "name": "Pure Souls", "time": "5:58" },
    { "name": "Ok Ok", "time": "3:24" },
    { "name": "New Again", "time": "3:03" },
    { "name": "Jesus Lord", "time": "9:33" },
    { "name": "Every Hour", "time": "1:52" },
    { "name": "Selah", "time": "2:44" },
    { "name": "Follow God", "time": "1:44" },
    { "name": "Closed On Sunday", "time": "2:31" },
    { "name": "On God", "time": "2:16" },
    { "name": "Everything We Need", "time": "1:56" },
    { "name": "Water", "time": "2:48" },
    { "name": "God Is", "time": "3:23" },
    { "name": "Hands On", "time": "3:23" },
    { "name": "Use This Gospel", "time": "3:33" },
    { "name": "Jesus Is Lord", "time": "0:49" },
    { "name": "I Thought About Killing You", "time": "4:34" },
    { "name": "Yikes", "time": "3:08" },
    { "name": "All Mine", "time": "2:25" },
    { "name": "Wouldn't Leave", "time": "3:25" },
    { "name": "No Mistakes", "time": "2:03" },
    { "name": "Ghost Town", "time": "4:31" },
    { "name": "Violent Crimes", "time": "3:35" },
    { "name": "Ultralight Beam", "time": "5:20" },
    { "name": "Father Stretch My Hands", "time": "2:15" },
    { "name": "Famous", "time": "3:16" },
    { "name": "Feedback", "time": "2:27" },
    { "name": "Low Lights", "time": "2:11" },
    { "name": "Highlights", "time": "3:19" },
    { "name": "Freestyle 4", "time": "2:03" },
    { "name": "I Love Kanye", "time": "0:44" },
    { "name": "Waves", "time": "3:01" },
    { "name": "FML", "time": "3:56" },
    { "name": "Real Friends", "time": "4:11" },
    { "name": "Wolves", "time": "5:01" },
    { "name": "Frank's Track", "time": "0:38" },
    { "name": "30 Hours", "time": "5:23" },
    { "name": "No More Parties In LA", "time": "6:14" },
    { "name": "Facts (Charlie Heat Version)", "time": "3:20" },
    { "name": "Fade", "time": "3:13" },
    { "name": "Saint Pablo", "time": "6:12" },
    { "name": "On Sight", "time": "2:36" },
    { "name": "Black Skinhead", "time": "3:08" },
    { "name": "I Am A God", "time": "3:51" },
    { "name": "New Slaves", "time": "4:16" },
    { "name": "Hold My Liquor", "time": "5:26" },
    { "name": "I'm In It", "time": "3:54" },
    { "name": "Blood On The Leaves", "time": "5:59" },
    { "name": "Guilt Trip", "time": "4:03" },
    { "name": "Send It Up", "time": "2:58" },
    { "name": "Bound 2", "time": "3:49" },
    { "name": "No Church In The Wild", "time": "4:32" },
    { "name": "Lift Off", "time": "4:26" },
    { "name": "Ni**as In Paris", "time": "3:39" },
    { "name": "Otis", "time": "2:58" },
    { "name": "Gotta Have It", "time": "2:20" },
    { "name": "New Day", "time": "4:32" },
    { "name": "That's My Bitch", "time": "3:22" }
]